#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Live Coolify secrets must not land in local `.env` (that file is Compose on
# localhost). `.env.production` is gitignored via `.env.*`.
ENV_FILE=".env.production"

TOTAL_STAGES=7

banner "Coolify Playground production"

# ── 1. Release path is a PR into main ────────────────────────────────────
stage "Release path: develop → main"
say "Production starts with a release PR, not a direct push and not a develop merge."
open_url "https://github.com/prela/enterprise-nuxt-starter/settings/branches"
step "Confirm main requires a pull request (no direct push). develop → main is the release PR."
step "hotfix/* may also target main; feature branches never do."
step "This work package itself PRs into develop. The first production tag comes after a later release PR."
pause "Press Enter after main is protected."

# ── 2. Coolify dashboard ─────────────────────────────────────────────────
stage "Coolify dashboard URL"
say "Same Coolify instance as preview. Production is a second application, not a second server."
ask COOLIFY_URL "Paste the Coolify dashboard origin (e.g. https://coolify.example.com):"
COOLIFY_URL="${COOLIFY_URL%/}"
write_env COOLIFY_URL "$COOLIFY_URL"

# ── 3. Public HTTPS origin ───────────────────────────────────────────────
stage "Production HTTPS origin"
say "One origin, three places: Coolify domain, NUXT_PUBLIC_SITE_URL, GitHub PRODUCTION_URL."
say "Use a different hostname than preview. No trailing slash."
ask PRODUCTION_URL "Paste the production origin (e.g. https://playground.example.com):"
PRODUCTION_URL="${PRODUCTION_URL%/}"
write_env PRODUCTION_URL "$PRODUCTION_URL"

# ── 4. Identity secret (not preview's) ─────────────────────────────────
stage "Generate production Identity secret"
say "A separate Better Auth secret from preview. Production Postgres is this app's volume."
note "Written to $ENV_FILE (gitignored). Do not copy it into git."
NUXT_BETTER_AUTH_SECRET="$(_existing NUXT_BETTER_AUTH_SECRET || true)"
if [[ -z "$NUXT_BETTER_AUTH_SECRET" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    NUXT_BETTER_AUTH_SECRET="$(openssl rand -hex 32)"
  else
    ask_secret NUXT_BETTER_AUTH_SECRET "openssl missing; paste a 32+ character NUXT_BETTER_AUTH_SECRET:"
  fi
else
  note "Keeping existing NUXT_BETTER_AUTH_SECRET from $ENV_FILE."
fi
write_env NUXT_BETTER_AUTH_SECRET "$NUXT_BETTER_AUTH_SECRET"
say "Copy these into Coolify in the next stage:"
step "NUXT_BETTER_AUTH_SECRET=$NUXT_BETTER_AUTH_SECRET"
step "NUXT_PUBLIC_SITE_URL=$PRODUCTION_URL"
step "Do not paste POSTGRES_* or DATABASE_URL; compose uses Coolify SERVICE_USER_POSTGRES / SERVICE_PASSWORD_POSTGRES."
pause "Press Enter after you have copied them somewhere safe."

# ── 5. Create the Coolify application ─────────────────────────────────────
stage "Create Coolify production application"
say "Public GitHub repo; standing Playground from main. Auto Deploy stays off."
open_url "$COOLIFY_URL"
step "Open the project (the same one as preview is fine)."
step "Click + New, then Public Repository."
step "Repository URL: https://github.com/prela/enterprise-nuxt-starter"
step "Branch: main  (not develop)."
step "Server: the Hetzner VPS that should serve production."
step "Build pack: Docker Compose."
step "Base directory: /"
step "Compose file: /compose.preview.yaml  (same topology as preview; this is a separate application)."
step "If you see Preview Deployments (per-PR URLs), leave that OFF."
pause "Press Enter after the application exists and is saved."

# ── 6. Domain, env, Auto Deploy off, webhook ────────────────────────────────
stage "Domain, env, webhook"
say "Proxy talks to playground:3000. Postgres must not have a public domain."
open_url "$COOLIFY_URL"
step "Open the playground service (not postgres)."
step "Set Domains to $PRODUCTION_URL — if the field needs a container port, use ${PRODUCTION_URL}:3000."
step "Environment Variables — add exactly these names (mark the secret hidden if the UI can):"
step "  NUXT_BETTER_AUTH_SECRET"
step "  NUXT_PUBLIC_SITE_URL=$PRODUCTION_URL"
step "Advanced → Auto Deploy: OFF. Merges to main must not ship; only a SemVer tag does."
step "Copy the Deploy Webhook URL Coolify shows (application → Webhooks / Deploy)."
ask_secret COOLIFY_PRODUCTION_WEBHOOK "Paste the Coolify production deploy webhook URL:"
set_secret COOLIFY_PRODUCTION_WEBHOOK "$COOLIFY_PRODUCTION_WEBHOOK"
pause "Press Enter after domain, env, Auto Deploy off, and webhook are saved."

# ── 7. GitHub PRODUCTION_URL and how to tag ───────────────────────────────
stage "GitHub PRODUCTION_URL and first tag"
say "CI reads vars.PRODUCTION_URL (a variable, not a secret). Changelog input stays Conventional Commits."
write_env PRODUCTION_URL "$PRODUCTION_URL"
set_var PRODUCTION_URL "$PRODUCTION_URL"
open_url "https://github.com/prela/enterprise-nuxt-starter/settings/variables/actions"
step "If gh skipped the variable: New repository variable → Name PRODUCTION_URL → Value $PRODUCTION_URL"
say "After this work package is on develop, cut production like this:"
step "Open a PR develop → main (not a direct push). Wait until check ci is green, then merge."
step "On main, tag the merge commit immediately: git tag -a v0.y.z -m v0.y.z  (must be origin/main's tip)."
step "Match v0.y.z to the lockstep version in layers/*/package.json. Do not bump to v1.0.0 yet."
step "git push origin v0.y.z  — that run deploys Coolify, then pnpm smoke against PRODUCTION_URL."
step "Commit messages (feat:/fix:/BREAKING CHANGE:) are the changelog; do not invent CalVer or work-package tags."
pause "Press Enter after PRODUCTION_URL is set. Tag only after a release PR is on main."

# ──────────────────────────────────────────────────────────────────────────

finish
say "Ticket 15 is ready to tag after a develop → main release PR."
